cmake: alias qtadvanceddocking to qt(5|6)advanceddocking for compatability
githubuser0xFFFF/Qt-Advanced-Docking-System pull request #517
Opened 2023-05-20 19:30 UTC by FelixBer

alias qtadvanceddocking to qt(5|6)advanceddocking for backwards compatibility.

Current master breaks all cmake projects and would force them to commit to either the qt5 or qt6 target, or use qt{QT_VERSION_MAJOR}advanceddocking to select the qt version automatically.
Since the latter is what should be reasonably expected (i think) an alias would maintain compatibility.
If a specific qt version is desired one can still switch to the specific target.

ref https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/489

2023-05-23 07:58 UTC, n-elie requested changes

2023-05-23 07:58 UTC, n-elie commented on src/CMakeLists.txt
> +add_library(qtadvanceddocking ALIAS ${library_name})
```
if(QT_VERSION_MAJOR STREQUAL "5")
    # alias qtadvanceddocking to qt5advanceddocking for compatibility
    add_library(qtadvanceddocking ALIAS ${library_name})
endif()
```

2023-05-23 11:02 UTC, FelixBer commented on src/CMakeLists.txt
> +add_library(qtadvanceddocking ALIAS ${library_name})
library_name is qt{QT_VERSION_MAJOR}advanceddocking, so it should take whatever is selected by cmake.

2023-05-23 11:06 UTC, n-elie commented on src/CMakeLists.txt
> +add_library(qtadvanceddocking ALIAS ${library_name})
Yes but the alias will be the same for both versions. Will it be an alias to qt5advanceddocking or qt6advanceddocking if you install both q5 and qt6 versions?

2023-05-25 06:17 UTC, n-elie commented on src/CMakeLists.txt
> +add_library(qtadvanceddocking ALIAS ${library_name})
conda-forge has both versions that can be installed together: https://anaconda.org/search?q=advanced-docking-system

2023-05-29 19:43 UTC, FelixBer commented on src/CMakeLists.txt
> +add_library(qtadvanceddocking ALIAS ${library_name})
I am not familiar with conda, but cmake can only select qt5 or qt6, so whatever qt version is currently selected by find_package should be targeted by the qtadvanceddocking target imo. maybe i am missing something.

2023-05-30 07:14 UTC, n-elie commented on src/CMakeLists.txt
> +add_library(qtadvanceddocking ALIAS ${library_name})
Qt5 and Qt6 versions are compiled separately but, then,  the binary packages can be installed in parallel.

2023-09-05 08:07 UTC, closed without merging